### ISSUE TITLE
No pointcloud received from rotors_simulation

### ISSUE THREAD

**Issue by appie-17** [ethz-asl/mav_voxblox_planning#28]
Running the LOCO planning as described, by installing the rotors simulator and running `roslaunch mav_local_planner firefly_sim.launch`. Which results in the Gazebo window showing up. However no incoming messages seem to exist on either the `/firefly/pointcloud` or `/firefly/vi_sensor/camera_depth/depth/points` topic. Further I am able to visualize the stereo camera topic directly within Gazebo. Am I missing any additional steps/procedures to get the local planning module running?

**Comment by appie-17** [comment]
Solved the issue, I was missing the `ros-kinetic-gazebo-plugins`.

**Comment by jwangjie** [comment]
Hi @appie-17,  

I wonder can I ask you a question about using "Local Planning"? I followed the instructions and launched the gazebo window normally. However, I don't have topic `/firefly/voxblox_node/mesh` in rviz, and there are also no point clouds shown in rivz. There are no response by using `Send Waypoint`, but the drone in Gazebo have responses by using `Send to Controller`. I wonder do you know any potential reason for this?  Thank you very much.

Regards,
Jie
