### ISSUE TITLE
voxblox_skeleton_planner/skeleton does not appear in rviz because edge point is empty

### ISSUE THREAD

**Issue by bangyanz** [ethz-asl/mav_voxblox_planning#33]
I was running the skeleton planner and everything is fine except the skeleton diagram points. First of all, they are published as pointcloud points in ROS but no actual message is passed.
I debugged further and noticed that skeleton_generator_.getSkeleton().getEdgePoints() is empty.
Then I checked void SkeletonGenerator::updateSkeletonFromLayer() and found no skeleton point is classified as either edge or vertex. 
Initially I thought it is because my generated skeleton map is wrong. So I used the rs_skeleton_0.10.voxblox and found the result to be the same. So I wonder why skeleton_layer couldn't read or get the edge points from the map? 

Thank you.

**Comment by bangyanz** [comment]
![image](https://user-images.githubusercontent.com/6415909/55383425-b8f51d80-555a-11e9-9291-dee6cd36cc1b.png)

**Comment by bangyanz** [comment]
I figured it out : 
In SkeletonGenerator::updateSkeletonFromLayer()
      // if (!skeleton_voxel.is_face) {
      //   continue;
      // }

you have to comment this code so you can see generated points

**Comment by jackykongfz** [comment]
Thanks for your solution a lot!
