### ISSUE TITLE
Could not contact ROS master at [http://localhost:11311], retrying...

### ISSUE THREAD

**Issue by mechaliomar** [ethz-asl/mav_voxblox_planning#37]
Any one experienced this problem and solved it?

**Comment by helenol** [comment]
You don't have a roscore running. :) 
http://wiki.ros.org/roscore
http://wiki.ros.org/ROS/Tutorials/UnderstandingNodes

**Comment by mechaliomar** [comment]
@helenol Thanks for your respond. I solved that problem by lunching roscore in one terminal and rviz in another terminal. But still have a problem, I cant do the following:

 In rviz, select Panels -> Add New Panel and select Planning Panel: 
I just have :
rviz
rviz_plugin_tutorials

BEST REGARDS

**Comment by RicoJia** [comment]
> You don't have a roscore running. :)
> http://wiki.ros.org/roscore
> http://wiki.ros.org/ROS/Tutorials/UnderstandingNodes
THANK YOU! WORKED FOR ME @helenol

**Comment by WohimLee** [comment]
> Any one experienced this problem and solved it?

same question

**Comment by ArifinRafi** [comment]
I am facing the same issue. How did you solve it?

**Comment by Jaeyoung-Lim** [comment]
@liheqian1993 @ArifinRafi Please read the linked document on the original reply.

The problem you are having is not related to this repository, but related to the startup sequence of ROS in general
