### ISSUE TITLE
Problem compiling with ros melodic

### ISSUE THREAD

**Issue by Leppy-tech** [ethz-asl/mav_voxblox_planning#54]
Hey,
When compiling on ROS melodic, when I get to the mav_trajectory_generation package, it fails and account of yaml dependency. The terminal looks like that:

CMake Error at /home/test/catkin_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findyaml_cpp_catkin.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "yaml_cpp_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "yaml_cpp_catkin"
  with any of the following names:

    yaml_cpp_catkinConfig.cmake
    yaml_cpp_catkin-config.cmake

  Add the installation prefix of "yaml_cpp_catkin" to CMAKE_PREFIX_PATH or
  set "yaml_cpp_catkin_DIR" to a directory containing one of the above files.
  If "yaml_cpp_catkin" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)

Do you have any idea whats happening?
I've installed yaml-cpp

**Comment by rikba** [comment]
Hi

as a quick workaround, can you try to comment out the `yaml_cpp_catkin` in the `mav_trajectory_generation` `package.xml`?
https://github.com/ethz-asl/mav_trajectory_generation/blob/master/mav_trajectory_generation/package.xml#L22

**Comment by Leppy-tech** [comment]
Thank you, it seems to work!
