### ISSUE TITLE
build error and warning

### ISSUE THREAD

**Issue by daiwj5** [ethz-asl/mav_voxblox_planning#57]
Hey, my friends. I've cloned all code files correctly, and when i started to build , it appeared an error below:
_____________________________________________________________________________________________
Errors     << nlopt:make /root/Desktop/catkin_ws/logs/nlopt/build.make.000.log               
--2020-02-12 13:56:50--  https://github.com/ethz-asl/thirdparty_library_binaries/raw/master/nlopt-2.4.2.tar.gz
Resolving github.com (github.com)... 52.74.223.119
Connecting to github.com (github.com)|52.74.223.119|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/ethz-asl/thirdparty_library_binaries/master/nlopt-2.4.2.tar.gz [following]
--2020-02-12 13:56:51--  https://raw.githubusercontent.com/ethz-asl/thirdparty_library_binaries/master/nlopt-2.4.2.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.228.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.228.133|:443... failed: Connection refused.
make[2]: *** [nlopt_src-prefix/src/nlopt_src-stamp/nlopt_src-download] Error 4
make[1]: *** [CMakeFiles/nlopt_src.dir/all] Error 2
make: *** [all] Error 2
cd /root/Desktop/catkin_ws/build/nlopt; catkin build --get-env nlopt | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.............................................................................................
Failed     << nlopt:make                                   [ Exited with code 2 ]            
Failed    <<< nlopt                                        [ 3.1 seconds ]                   
Abandoned <<< eigen_catkin                                 [ Unrelated job failed ]          
Abandoned <<< gflags_catkin                                [ Unrelated job failed ]          
Abandoned <<< voxblox_msgs                                 [ Unrelated job failed ]          
Abandoned <<< mav_planning_msgs                            [ Unrelated job failed ]          
Abandoned <<< glog_catkin                                  [ Unrelated job failed ]          
Abandoned <<< ceres_catkin                                 [ Unrelated job failed ]          
Abandoned <<< eigen_checks                                 [ Unrelated job failed ]          
Abandoned <<< mav_visualization                            [ Unrelated job failed ]          
Abandoned <<< minkindr                                     [ Unrelated job failed ]          
Abandoned <<< minkindr_conversions                         [ Unrelated job failed ]          
Abandoned <<< mav_trajectory_generation                    [ Unrelated job failed ]          
Abandoned <<< loco_planner                                 [ Unrelated job failed ]          
Abandoned <<< mav_planning_common                          [ Unrelated job failed ]          
Abandoned <<< mav_planning_rviz                            [ Unrelated job failed ]          
Abandoned <<< mav_trajectory_generation_ros                [ Unrelated job failed ]          
Abandoned <<< mav_path_smoothing                           [ Unrelated job failed ]          
Abandoned <<< voxblox                                      [ Unrelated job failed ]          
Abandoned <<< voxblox_rviz_plugin                          [ Unrelated job failed ]          
Abandoned <<< voxblox_ros                                  [ Unrelated job failed ]          
Abandoned <<< voxblox_planning_common                      [ Unrelated job failed ]          
Abandoned <<< voxblox_loco_planner                         [ Unrelated job failed ]          
Abandoned <<< mav_local_planner                            [ Unrelated job failed ]          
Abandoned <<< voxblox_rrt_planner                          [ Unrelated job failed ]          
Abandoned <<< voxblox_skeleton                             [ Unrelated job failed ]          
Abandoned <<< voxblox_skeleton_planner                     [ Unrelated job failed ]          
Abandoned <<< mav_planning_benchmark                       [ Unrelated job failed ]          
[build] Summary: 2 of 29 packages succeeded.                                                 
[build]   Ignored:   6 packages were skipped or are blacklisted.                             
[build]   Warnings:  None.                                                                   
[build]   Abandoned: 26 packages were abandoned.                                             
[build]   Failed:    1 packages failed.                                                      
[build] Runtime: 18.5 seconds total.                                                         
[build] Note: Workspace packages have changed, please re-source setup files to use them.

after i re-sourced set up files and rebuild, it threw warnings like:
_____________________________________________________________________________________________
Warnings   << nlopt:make /root/Desktop/catkin_ws/logs/nlopt/build.make.001.log               
--2020-02-12 13:57:56--  https://github.com/ethz-asl/thirdparty_library_binaries/raw/master/nlopt-2.4.2.tar.gz
Resolving github.com (github.com)... 13.250.177.223
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/ethz-asl/thirdparty_library_binaries/master/nlopt-2.4.2.tar.gz [following]
--2020-02-12 13:57:57--  https://raw.githubusercontent.com/ethz-asl/thirdparty_library_binaries/master/nlopt-2.4.2.tar.gz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2361992 (2.3M) [application/octet-stream]
Saving to: ‘nlopt-2.4.2.tar.gz’

nlopt-2.4.2.tar.gz  100%[===================>]   2.25M  24.1KB/s    in 3m 58s  

2020-02-12 14:01:58 (9.70 KB/s) - ‘nlopt-2.4.2.tar.gz’ saved [2361992/2361992]

configure: WARNING: Python and Guile wrappers require --enable-shared; disabling
configure: WARNING: can't find mkoctfile: won't be able to compile GNU Octave plugin
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
……

i want to know why this happen and how to solve this problem, thanks!

**Comment by liuliucen** [comment]
Hello, have you solved this problem?

**Comment by daiwj5** [comment]
> Hello, have you solved this problem?

yes, i have solved this problem

**Comment by Super-Iron-Man** [comment]
@daiwj5 Hi,I encountered the same problem, how did you solve it?

**Comment by daiwj5** [comment]
> @daiwj5 Hi,I encountered the same problem, how did you solve it?

Actually, it's a connection problem for  me due to some overseas servers, maybe you should try  several times and change your network if needed.
