### ISSUE TITLE
Couldn't call service: /voxblox_rrt_planner/plan

### ISSUE THREAD

**Issue by BananaGorilla98** [ethz-asl/mav_voxblox_planning#66]
Greetings! I am following the "Try out RRT and Skeleton planning" tutorial and facing issue at the "Using RRT voxblox planner" part. 

The RRT output path is not shown after I pressed the "Planner Service" button as mentioned. The RVIZ reported a warning `Couldn't call service: /voxblox_rrt_planner/plan`. 

May I know how to solve this issue? Thank you!

OS: Ubuntu 20.04
ROS version: ROS Noetic

**Comment by Field-CR** [comment]
I met the same problem. Have you solved it?
OS: Ubuntu 18.04
ROS version: ROS Melodic

**Comment by Ethereal-Tian** [comment]
The start pose you set maybe occupied. You can change the start pose and try again!

**Comment by BananaGorilla98** [comment]
Ok. It is solved. Thanks!
