### ISSUE TITLE
small error issue in voxblox_skeleton

### ISSUE THREAD

**Issue by Duckyu** [ethz-asl/mav_voxblox_planning#72]
Hi, I found out the error keep comes out.

`mav_voxblox_planning/voxblox_skeleton/src/io/skeleton_io.cpp:72:75: error: cannot convert ‘uint32_t* {aka unsigned int*}’ to ‘uint64_t* {aka long unsigned int*}’ for argument ‘3’ to ‘bool voxblox::utils::readProtoMsgFromStream(std::istream*, google::protobuf::Message*, uint64_t*)’`

Therefore, I changed the line 69: from **uint32_t tmp_byte_offset = 0;** into  **uint64_t tmp_byte_offset = 0;** and successed to build.

I share this info with the other person who has the same problem.

I apologize if I ruined the GitHub community's rule. (I don't know where to share this kind of info.)

**Comment by Hao-Starrr** [comment]
It works! Thank you!

**Comment by Royboy1998** [comment]
Thanks it really helps!
